# Generated by Django 3.0.3 on 2020-07-16 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200716_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='fest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_app.CollegeModel'),
        ),
    ]
