# Generated by Django 3.0.3 on 2020-07-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200716_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='fest',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.CollegeModel'),
        ),
    ]
