# Generated by Django 3.0.3 on 2020-07-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20200716_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='cricketmodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
    ]
