# Generated by Django 3.0.3 on 2020-07-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_cricketmodel_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='badmintonmodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='basketballmodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='footballmodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='hockeymodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='kabaddimodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='tabletennismodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
        migrations.AddField(
            model_name='volleymodel',
            name='inst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.RegistrationModel'),
        ),
    ]
