# Generated by Django 3.0.3 on 2020-07-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20200719_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volleymodel',
            name='p10',
        ),
    ]
